
#### get all books
get http://localhost:8000/books
Content-Type: application/json

{
  "page":"1",
  "size":"5"
}

#### post book
post http://localhost:8000/books
Content-Type: application/json

{
    "title": "g",
    "description": "otro libro",
    "stock": 3,
    "salePrice": 450.50,
    "available": true
}


#### put
put http://localhost:8000/books/1
Content-Type: application/json

{
    "title": "GASH",
    "description": "otro libro",
    "stock": 3,
    "salePrice": 450.50,
    "available": true
}


#### delete
delete http://localhost:8000/books/1


#### patch
patch http://localhost:8000/books/1
Content-Type: application/json

{
    "title": "gashapar"
}

####
post http://localhost:8000/sales
Content-Type: application/json

{
    "bookId": 1,
    "customerEmail": "gashapar"
}


####
post http://localhost:8000/likes
Content-Type: application/json

{
    "bookId": 1,
    "customerEmail": "gaspari"
}
